### PR TITLE
this is not used too

### PR DESCRIPTION
**Pull request by zPeanut**

### CODE REVIEW

**Comment by LeafHacker** [comment]
As per #40, removing stuff in Resources can break older versions of impact. We should consider which (if any) versions use this before removing.

**Comment by ZeroMemes** [comment]
No versions use this, the plan was for future versions to tho loll

**Comment by LeafHacker** [comment]
> No versions use this

in that case why not merge?

**Comment by zPeanut** [comment]
why isnt this merged if no versions use this?

**Pull request merged**
