### PR TITLE
add random backgrounds

### PR DESCRIPTION
**Pull request by EvilSourcerer**
cool

### CODE REVIEW

**Comment by EvilSourcerer** [comment]
bro this PR is still better than the current version plz accept

**Comment by ZeroMemes** [comment]
image
what the fuck?

**Comment by EvilSourcerer** [comment]
srry for that, now deleted please reopen ❤️

**Comment by leijurv** [comment]
no lol, we already have the images

**Comment by EvilSourcerer** [comment]
font colors. in the json.

**Comment by leijurv** [comment]
not merging a copy of all the images

**Comment by EvilSourcerer** [comment]
fine by me. new PR time.

**Pull request closed without merging**
