### PR TITLE
Cape Designs Attempt 3

### PR DESCRIPTION
**Pull request by EmeraldSnorlax**
https://imgur.com/a/CmsvNBW

### CODE REVIEW

**Comment by zPeanut** [comment]
we do not accept the support cape as we dont associate any of our staff as disabled (with few exceptions.) closed until the staff cape is changed.

**Comment by zPeanut** [comment]
we'll gladly accept the developer and donator capes though

**Comment by EmeraldSnorlax** [comment]
#25

**Comment by SpicyBigGithub** [comment]
Still better

**Comment by EmeraldSnorlax** [comment]
@zPeanut #25

**Comment by leijurv** [comment]
> we do not accept the support cape as we dont associate any of our staff as disabled (with few exceptions.) closed until the staff cape is changed.


wtfr*ck i liked wheelchair cape

**Comment by SpicyBigGithub** [comment]
Approve it anyway

**Pull request closed without merging**
