### PR TITLE
New cape designs

### PR DESCRIPTION
**Pull request by EmeraldSnorlax**
https://imgur.com/a/FcL3dIa
New cape designs + .xcf file

### CODE REVIEW

**Comment by SpicyBigGithub** [comment]
New capes when

**Comment by EmeraldSnorlax** [comment]
Nevermind - just realised that the text is aligned differently on the donator cape. I'll close this PR and reopen it when I fix it when I get home

**Comment by EmeraldSnorlax** [comment]
Odd -- turns out it is centered. I'm just seeing things

**Comment by SpicyBigGithub** [comment]
Wheelchair capes>>

**Comment by EmeraldSnorlax** [comment]
Wheelchair capes look utterly trash
https://cdn.discordapp.com/attachments/308653317834145802/591918524671197184/unknown.png
@usereewrjrjeejr

**Comment by EmeraldSnorlax** [comment]
Adding a wheelchair cape
#23

**Pull request closed without merging**
